# Lesson 1 Practice: NumPy Part 1
Use this notebook to follow along with the lesson in the corresponding lesson notebook: [L01-Numpy_Part1-Lesson.ipynb](./L01-Numpy_Part1-Lesson.ipynb).  



## Instructions
Follow along with the teaching material in the lesson. Throughout the tutorial sections labeled as "Tasks" are interspersed and indicated with the icon: ![Task](http://icons.iconarchive.com/icons/sbstnblnd/plateau/16/Apps-gnome-info-icon.png). You should follow the instructions provided in these sections by performing them in the practice notebook.  When the tutorial is completed you can turn in the final practice notebook. For each task, use the cell below it to write and test your code.  You may add additional cells for any task as needed or desired.  

## Task 1a: Setup

In the practice notebook, import the following packages:
+ `numpy` as `np`

In [2]:
import numpy as np

## Task 2a: Creating Arrays

In the practice notebook, perform the following.  
- Create a 1-dimensional numpy array and print it.
- Create a 2-dimensional numpy array and print it.
- Create a 3-dimensional numpy array and print it.

In [3]:
my_array = np.array([1,2,3,4,5])
my_2D_array = np.array([[1,2,3],[4,5,6]])
my_3D_array = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print(my_array)
print(my_2D_array)
print(my_3D_array)


[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


## Task 3a: Accessing Array Attributes

In the practice notebook, perform the following.

- Create a NumPy array.
- Write code that prints these attributes (one per line): `ndim`, `shape`, `size`, `dtype`, `itemsize`, `data`, `nbytes`.
- Add a comment line, before each line describing what value the attribute returns. 


In [4]:
array = np.array([1,2,3,4,5,6,7,8,9,10])

print(array.ndim)
print(array.shape)
print(array.size)
print(array.dtype)
print(array.itemsize)
print(array.data)
print(array.nbytes)

1
(10,)
10
int64
8
80


## Task 4a: Initializing Arrays

In the practice notebook, perform the following.

+ Create an initialized array by using these functions:  `ones`, `zeros`, `empty`, `full`, `arange`, `linspace` and `random.random`. Be sure to follow each array creation with a call to `print()` to display your newly created arrays. 
+ Add a comment above each function call describing what is being done.  

In [14]:
ones = np.ones(5)
#creating an arry of 1 with 5 columns
zeros = np.zeros((3,4))
#create a 3x4 array with zeros
empty = np.empty((2,2))
#create a 2x2 empty array with random input
full = np.full((3,2),10)
#create a full 3,2 array with 10 as input
linspace = np.linspace(2, 10, num = 2)
#create an 1x2 array start with 2 and end with 10
random = np.random.random()
#create a random array
arrange = np.array((3,7))
#create a 1D array with 3 and 7

print(ones)
print(zeros)
print(empty)
print(full)
print(linspace)
print(random)
print(arrange)

[1. 1. 1. 1. 1.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 0.]
 [0. 0.]]
[[10 10]
 [10 10]
 [10 10]]
[ 2. 10.]
0.0003342018884384679
[3 7]


## Task 5a:  Broadcasting Arrays

In the practice notebook, perform the following.

+ Create two arrays of differing sizes but compatible with broadcasting.
+ Perform addition, multiplication and subtraction.
+ Create two additional arrays of differing size that do not meet the rules for broadcasting and try a mathematical operation.  

In [19]:
array_1 = np.array([1,2,3])
array_2 = np.full((2,3),5)

print(f"array_1 shape: {array_1}")
print(f"array_2 shape: {array_2}")

print(array_1 + array_2)
print(array_1 - array_2)
print(array_1 * array_2)

array_1 shape: [1 2 3]
array_2 shape: [[5 5 5]
 [5 5 5]]
[[6 7 8]
 [6 7 8]]
[[-4 -3 -2]
 [-4 -3 -2]]
[[ 5 10 15]
 [ 5 10 15]]


In [24]:
array_3 = np.array([[1,2,3],[4,5,7]])
array_4 = np.full((2,4),5)

print(f"array_1 shape: {array_3}")
print(f"array_2 shape: {array_4}")

print(array_3 + array_4)
#operands could not be broadcast together with shapes (2,3) (2,4)
print(array_3 + array_4)
#operands could not be broadcast together with shapes (2,3) (2,4)
print(array_3 + array_4)
#operands could not be broadcast together with shapes (2,3) (2,4)

array_1 shape: [[1 2 3]
 [4 5 7]]
array_2 shape: [[5 5 5 5]
 [5 5 5 5]]


ValueError: operands could not be broadcast together with shapes (2,3) (2,4) 

## Task 6a: Math/Stats Aggregate Functions

In the practice notebook, perform the following.

+ Create three to five arrays
+ Experiment with each of the aggregation functions: `sum`, `minimum`, `maximum`, `cumsum`, `mean`, `np.corrcoef`, `np.std`, `np.var`. 
+ For each function call, add a comment line above it that describes what it does.  
```


In [13]:
array = np.array([[1,2,3],[4,5,6]])

#print the sum of the two array and return an interger
print(np.sum(array))
#print the smallest list 
print(np.minimum([1,2,3],[4,5,6]))
#print the biggest list
print(np.maximum([1,2,3],[4,5,6]))
#print the cummulative sum of the two array starting from the smallest 
print(np.cumsum(array))
#print the mean of the two array
print(np.mean(array))
#print the correlation coefficients betwwen the 2 array
print(np.corrcoef(array))
#compute the standard deviation along the specified axis
print(np.std(array))
compute the variance along the specified axis 
print(np.var(array))
print(array)

21
[1 2 3]
[4 5 6]
[ 1  3  6 10 15 21]
3.5
[[1. 1.]
 [1. 1.]]
1.707825127659933
2.9166666666666665
[[1 2 3]
 [4 5 6]]


## Task 6b: Logical Aggregate Functions

In the practice notebook, perform the following.

+ Create two arrays containing boolean values.
+ Experiment with each of the aggregation functions: `logical_and`, `logical_or`, `logical_not`. 
+ For each function call, add a comment line above it that describes what it does.  
```

In [18]:
array = (True, False, True, True, False)
array_2 = (True, True, False, False, False)

#return the logical and of each array
print(np.logical_and(array, array_2))
#return the logical or between each array
print(np.logical_or(array, array_2))
#return the opposite value of the named array
print(np.logical_not(array))

[ True False False False False]
[ True  True  True  True False]
[False  True False False  True]
